### ISSUE TITLE
Python formatter undoes pylint-silent message control by re-flowing lines

### ISSUE THREAD

**Issue by jamesquilty** [udifuchs/pylint-silent#3]
Thanks for writing pylint-silent, I've trialled it on one of my repositories and believe it has _significant_ potential!

I've encountered a problematic interaction between pylint-silent and the Python formatter I use ([Black](https://github.com/psf/black), but it could be any formatter). The problem is:

1. pylint-silent _appends_ `  # pylint: disable=...` comments to lines flagged by pylint, creating some lines which exceed the formatter's line-length threshold,
2. running the formatter re-flows the long lines created by pylint-silent into shorter multiple-line statements with the appended comment on the _last_ line,
3. pylint then flags rule violations in the lines _preceding_ the `pylint: disable=...` comments which the comment was supposed to suppress.

I found it's possible to work-around this issue (see below) but it seems to me that this issue could be avoided by pylint-silent adding its message control comments as an individual full line preceding the line which pylint flagged, using (note the `-next` part of the pylint message control statement):
```python
# pylint: disable-next=...
```
According to the pylint documentation <https://pylint.pycqa.org/en/v2.17.3/user_guide/messages/message_control.html#block-disables> this usage will disable "all the violations on the following line" _only_. 

Such a line would be much less likely to exceed formatter line length thresholds.

A quick look at the source code indicates that this would be _really_ easy to change in `pylint-silent apply ...` but I'm not sure whether it would be problematic for `pylint-silent reset ...`? Potentially, as the message control comments would then be added as individual lines it would make `reset` easier?

What do you think about changing pylint-silent from _appending_ `  # pylint: disable=...` to _inserting_ `# pylint: disable-next=...` lines?

**Work-around:** performing the following until pylint no longer flags rule violations worked on the single repository on which I tried it, but may not work on all cases:

```shell
find src -name "*.py" -exec pylint-silent reset {} +
pylint-silent apply <(pylint src)
black src
pylint src
```

**Comment by udifuchs** [comment]
> What do you think about changing pylint-silent from _appending_ ` # pylint: disable=...` to _inserting_ `# pylint: disable-next=...` lines?

I wasn't aware of the `disable-next` option. It is a good idea to use it, but it would be annoying for existing users (myself included) to have every pylint comment changed.

A good way to keep backward compatibility would be to add a '--line-length' option. Then, if adding the `# pylint: disable` comment would make the line longer than the specified length, pylint-silent would add a `#pylint: disable-next` comment instead.

Having a default line length of something like 999 would preserve backward compatibility.

Would you like to contribute a patch? If not, I'll try to implement it in the next few days.
