### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by serjflint** [udifuchs/pylint-silent#8]
Hello! Thank you for a great Python library. It is very helpful for large codebases.

To the point. pypi.org mentions "GNU General Public License v2 or later (GPLv2+) (GPL-2.0-or-later)" but I can't find it in the repo.

Do you consider switching to MIT or Apache and adding the LICENSE file to the repo?

**Comment by udifuchs** [comment]
> Do you consider switching to MIT or Apache and adding the LICENSE file to the repo?

Considering that pylint is GPLv2, I do not see any advantage in switching to a different license.
I will add a LICENSE file soon.
